package com.github.aqiu202.ideayapi.config.ui;

import com.github.aqiu202.ideayapi.util.StringUtils;
import com.intellij.openapi.actionSystem.ActionToolbarPosition;
import com.intellij.openapi.ui.ComboBox;
import com.intellij.ui.DoubleClickListener;
import com.intellij.ui.ToolbarDecorator;
import com.intellij.ui.components.JBList;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Enumeration;
import java.util.StringJoiner;

/**
 * 配置面板
 */
public class YApiConfigurationForm {

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(2, 5, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(10, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel.add(panel1, new GridConstraints(0, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(264, 115), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("项目token：");
        panel1.add(label1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("项目ID：");
        panel1.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("YApi地址：");
        panel1.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        urlField = new JTextField();
        panel1.add(urlField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tokenField = new JTextField();
        tokenField.setDropMode(DropMode.INSERT);
        panel1.add(tokenField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        enableBasicScopeCheckBox = new JCheckBox();
        enableBasicScopeCheckBox.setText("是否自动添加数字类型参数的范围描述");
        panel1.add(enableBasicScopeCheckBox, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel1.add(projectIdField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("接口字段命名策略：");
        panel1.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel1.add(namingStrategyComboBox, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("参数解析方式：");
        panel1.add(label5, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel1.add(dataModeComboBox, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        enableTypeDescCheckBox = new JCheckBox();
        enableTypeDescCheckBox.setSelected(false);
        enableTypeDescCheckBox.setText("是否将请求参数类型信息拼接到字段描述");
        panel1.add(enableTypeDescCheckBox, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        useMethodDefineAsRemarkCheckBox = new JCheckBox();
        useMethodDefineAsRemarkCheckBox.setSelected(false);
        useMethodDefineAsRemarkCheckBox.setText("是否将接口定义信息设置为接口备注");
        panel1.add(useMethodDefineAsRemarkCheckBox, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ignoreViewUrlCheckBox = new JCheckBox();
        ignoreViewUrlCheckBox.setText("是否忽略非接口URL");
        panel1.add(ignoreViewUrlCheckBox, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        useLombokCheckBox = new JCheckBox();
        useLombokCheckBox.setText("是否启用Lombok支持");
        panel1.add(useLombokCheckBox, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel.add(panel2, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("请求忽略字段设置");
        panel2.add(label6, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setText("响应忽略字段设置");
        panel2.add(label7, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ignoredReqFieldsPanel = new JPanel();
        ignoredReqFieldsPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.add(ignoredReqFieldsPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        ignoredResFieldsPanel = new JPanel();
        ignoredResFieldsPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.add(ignoredResFieldsPanel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

    private JTextField urlField;
    private JTextField tokenField;
    private JCheckBox enableBasicScopeCheckBox;
    private JPanel panel;
    private JFormattedTextField projectIdField;
    private ComboBox<String> namingStrategyComboBox;
    private ComboBox<String> dataModeComboBox;
    private JCheckBox enableTypeDescCheckBox;
    private JCheckBox useMethodDefineAsRemarkCheckBox;
    private JCheckBox ignoreViewUrlCheckBox;
    private JCheckBox useLombokCheckBox;
    private JList<String> ignoredReqFields;
    private JPanel ignoredReqFieldsPanel;
    private JList<String> ignoredResFields;
    private JPanel ignoredResFieldsPanel;
    private DefaultListModel<String> ignoredReqFieldsModel;
    private DefaultListModel<String> ignoredResFieldsModel;

    public JPanel getPanel() {
        return panel;
    }

    public JTextField getUrlField() {
        return urlField;
    }

    public JFormattedTextField getProjectIdField() {
        return projectIdField;
    }

    public JTextField getTokenField() {
        return tokenField;
    }

    public ComboBox<String> getNamingStrategyComboBox() {
        return namingStrategyComboBox;
    }

    public JCheckBox getEnableBasicScopeCheckBox() {
        return enableBasicScopeCheckBox;
    }

    public JCheckBox getEnableTypeDescCheckBox() {
        return enableTypeDescCheckBox;
    }

    public ComboBox<String> getDataModeComboBox() {
        return dataModeComboBox;
    }

    public JCheckBox getUseMethodDefineAsRemarkCheckBox() {
        return useMethodDefineAsRemarkCheckBox;
    }

    public JCheckBox getIgnoreViewUrlCheckBox() {
        return ignoreViewUrlCheckBox;
    }

    public JCheckBox getUseLombokCheckBox() {
        return useLombokCheckBox;
    }

    public String getIgnoredReqFields() {
        return this.readListModelValue(this.ignoredReqFieldsModel);
    }

    public JPanel getIgnoredReqFieldsPanel() {
        return ignoredReqFieldsPanel;
    }

    public JPanel getIgnoredResFieldsPanel() {
        return ignoredResFieldsPanel;
    }

    public String getIgnoredResFields() {
        return this.readListModelValue(this.ignoredResFieldsModel);
    }

    private String readListModelValue(DefaultListModel<String> listModel) {
        Enumeration<String> elements = listModel.elements();
        StringJoiner joiner = new StringJoiner(",");
        while (elements.hasMoreElements()) {
            String element = elements.nextElement();
            joiner.add(element);
        }
        return joiner.toString();
    }

    public void setIgnoredReqFields(java.util.List<String> fields) {
        this.ignoredReqFieldsModel.clear();
        for (String field : fields) {
            this.ignoredReqFieldsModel.addElement(field);
        }
    }

    public void setIgnoredReqFieldsPanel(JPanel ignoredReqFieldsPanel) {
        this.ignoredReqFieldsPanel = ignoredReqFieldsPanel;
    }

    public void setIgnoredResFieldsPanel(JPanel ignoredResFieldsPanel) {
        this.ignoredResFieldsPanel = ignoredResFieldsPanel;
    }

    public void setIgnoredResFields(java.util.List<String> fields) {
        this.ignoredResFieldsModel.clear();
        for (String field : fields) {
            this.ignoredResFieldsModel.addElement(field);
        }
    }

    private void createUIComponents() {
        this.projectIdField = new JFormattedTextField(new DecimalFormat("#0"));
        this.projectIdField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                String old = projectIdField.getText();
                JFormattedTextField.AbstractFormatter formatter = projectIdField.getFormatter();
                if (!old.isEmpty()) {
                    if (formatter != null) {
                        String str = projectIdField.getText();
                        try {
                            long page = (Long) formatter.stringToValue(str);
                            projectIdField.setText(page + "");
                        } catch (ParseException pe) {
                            projectIdField.setText("1");//解析异常直接将文本框中值设置为1
                        }
                    }
                }
            }
        });
        this.namingStrategyComboBox = new ComboBox<>(
                new String[]{"None", "KebabCase", "SnakeCase", "LowerCase", "UpperCamelCase"});
        this.dataModeComboBox = new ComboBox<>(new String[]{"json-schema", "json5"});
        this.ignoredReqFieldsModel = new DefaultListModel<>();
        this.ignoredReqFields = this.createJList(this.ignoredReqFieldsModel);
        this.ignoredResFieldsModel = new DefaultListModel<>();
        this.ignoredResFields = this.createJList(this.ignoredResFieldsModel);
        new DoubleClickListener() {
            @Override
            protected boolean onDoubleClick(MouseEvent e) {
                return true;
            }
        }.installOn(ignoredResFields);

    }

    private JBList<String> createJList(ListModel<String> dataModel) {
        JBList<String> jbList = new JBList<>(dataModel);
        jbList.setEmptyText("空");
        jbList.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected,
                                                          boolean cellHasFocus) {
                final Component comp = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                setText(String.valueOf(value));
                return comp;
            }
        });
//        jbList.setFixedCellWidth(400);
//        jbList.setDragEnabled(true);
        jbList.setDropMode(DropMode.INSERT);
        return jbList;
    }

    public void init() {
        this.initPanel(this.ignoredReqFieldsPanel, this.ignoredReqFields, this.ignoredReqFieldsModel);
        this.initPanel(this.ignoredResFieldsPanel, this.ignoredResFields, this.ignoredResFieldsModel);
    }

    private void initPanel(JPanel jPanel, JList<String> jList, DefaultListModel<String> listModel) {
        jPanel.setEnabled(true);
        JPanel component = ToolbarDecorator.createDecorator(jList)
                .setPreferredSize(new Dimension(300, 200))
                .setToolbarPosition(ActionToolbarPosition.TOP)
                .setAddAction(button -> {
                    FieldEditor fieldEditor = new FieldEditor();
                    String text;
                    if (fieldEditor.showAndGet() && StringUtils.isNotBlank(text = fieldEditor.getText())) {
                        if (!listModel.contains(text)) {
                            listModel.addElement(text);
                        }
                    }
                }).createPanel();
        GridConstraints constraints = new GridConstraints();
        constraints.setAnchor(GridConstraints.ANCHOR_NORTHWEST);
        jPanel.add(component, constraints);
    }

}
